### ISSUE TITLE
run failed

### ISSUE THREAD

**Issue by Jetereting** [moqsien/xtray#1]
➜  xtray git:(main) ✗ go run .   
--# github.com/xtls/xray-core/proxy/wireguard
../../../go/pkg/mod/github.com/xtls/xray-core@v1.8.1/proxy/wireguard/tun.go:132:12: invalid operation: pkt == nil (mismatched types stack.PacketBufferPtr and untyped nil)

**Comment by moqsien** [comment]
> ➜ xtray git:(main) ✗ go run . --# github.com/xtls/xray-core/proxy/wireguard ../../../go/pkg/mod/github.com/xtls/xray-core@v1.8.1/proxy/wireguard/tun.go:132:12: invalid operation: pkt == nil (mismatched types stack.PacketBufferPtr and untyped nil)

That is a known bug from xray-core. I have raised an issue to xray-core, but its maintainer refused to repair it.
Anyway, you can comment out the code at  "pkt == nil" in xray-core.

**Comment by Jetereting** [comment]
> [gvc](https://github.com/moqsien/gvc) instead

How to instead by gvc?

**Comment by moqsien** [comment]
> > [gvc](https://github.com/moqsien/gvc) instead
> 
> How to instead by gvc?

Read the [docs](https://github.com/moqsien/gvc/blob/main/docs/Readme_CN.md).

**Comment by Jetereting** [comment]
> > > [gvc](https://github.com/moqsien/gvc) instead
> > 
> > 
> > How to instead by gvc?
> 
> Read the [docs](https://github.com/moqsien/gvc/blob/main/docs/Readme_CN.md).

➜  macos-amd64 ./gvc h
NAME:
   gvc host - Sytem hosts file management(need admistrator or root).

USAGE:
   gvc host command [command options] [arguments...]

COMMANDS:
   fetch, f      Fetch github hosts info.
   fetchall, fa  Get all github hosts info with no ping filters.
   show, s       Show hosts file path.
   help, h       Shows a list of commands or help for one command

OPTIONS:
   --help, -h  show help
➜  macos-amd64 ./gvc xray help
No help topic for 'xray'
➜  macos-amd64 ls
gvc
➜  macos-amd64 ./gvc xray help
No help topic for 'xray'

**Comment by moqsien** [comment]
> > > > [gvc](https://github.com/moqsien/gvc) instead
> > > 
> > > 
> > > How to instead by gvc?
> > 
> > 
> > Read the [docs](https://github.com/moqsien/gvc/blob/main/docs/Readme_CN.md).
> 
> ➜ macos-amd64 ./gvc h NAME: gvc host - Sytem hosts file management(need admistrator or root).
> 
> USAGE: gvc host command [command options] [arguments...]
> 
> COMMANDS: fetch, f Fetch github hosts info. fetchall, fa Get all github hosts info with no ping filters. show, s Show hosts file path. help, h Shows a list of commands or help for one command
> 
> OPTIONS: --help, -h show help ➜ macos-amd64 ./gvc xray help No help topic for 'xray' ➜ macos-amd64 ls gvc ➜ macos-amd64 ./gvc xray help No help topic for 'xray'

gvc help

gvc x

**Comment by Jetereting** [comment]
> 

work but no vpn.

:➜  macos-amd64 ./gvc x
>>> help

Commands:
  clear        clear the screen
  current      Show current vpn.
  exit         exit the program
  filter       Filter vpns by verifier.
  geoinfo      Download geoip.dat and geosite.dat for xray-core.
  help         display help
  omega        Download switchy-omega plugin for Google Chrome Browser.
  restart      Restart the running xray-core client.
  show         Show vpn list info.
  start        Start an xray-core client.
  status       Show xray-core client running status.
  stop         Stop the running xray-core client.


>>> status
xtray client is running.
xtray keeper is running.
>>> filter
verifier starts running.
>>> current
No vpn is choosen.
>>>
