### ISSUE TITLE
关于conf.txt来源的疑问

### ISSUE THREAD

**Issue by Jetereting** [moqsien/xtray#5]
1. xtray 取 conf.txt 为什么设计成从网络获取而不是通过 free 项目生成
2. free 项目生成 conf.txt 前为什么要做 AesEncrypt

**Comment by moqsien** [comment]
解耦。

free获取免费vpn比较慢，可能free自身还要使用vpn。
另外，free中考虑随时回去添加新的资源。无需为此去改xtray。
还有free获取的vpn并不会很快过期，也无需那么频繁地触发。

所以，这两者分开才是比较好的设计。你有自己的免费资源，就去fork free，然后自己维护。conf.txt的地址是可以配置的，换成自己维护的conf.txt地址就行了。

至于加密，是为了合规。不然直接被国内gitee干掉。
